apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-favorite-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/shadowrider-pl/gitops-cert-level-2-examples
    # targetRevision: main
    path: ./app-of-apps/my-app-list
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy: {}
