apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example04
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/shadowrider-pl/gitops-cert-level-2-examples
    # targetRevision: main
    path: ./sync-hooks-waves/04-handle-sync-fail
  destination:
    server: https://kubernetes.default.svc
    namespace: example04