apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: internal-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/shadowrider-pl/gitops-cert-level-2-examples
    # targetRevision: main
    path: ./simple-application
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy: 
    automated: {}